[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "pygapsgui/_version.py"
local_scheme = 'dirty-tag'
fallback_version = '3.1.0'
