# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\src\views\designer\mainwindow.ui'
#
# Created: Wed May  1 02:21:54 2019
#      by: pyside2-uic 2.0.0 running on PySide2 5.6.0~a1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from src.views.graph_view import GraphView


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(903, 470)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/designer/icons/01_Warning_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
    
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.gridExplorer = QtWidgets.QGridLayout()
        self.gridExplorer.setObjectName("gridExplorer")
        self.isoExplorer = QtWidgets.QListView(self.centralwidget)
        self.isoExplorer.setObjectName("isoExplorer")
        self.gridExplorer.addWidget(self.isoExplorer, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridExplorer, 0, 0, 1, 1)

        self.propertiesGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertiesGroup.sizePolicy().hasHeightForWidth())
        self.propertiesGroup.setSizePolicy(sizePolicy)
        self.propertiesGroup.setObjectName("propertiesGroup")
        self.gridProperties = QtWidgets.QGridLayout(self.propertiesGroup)
        self.gridProperties.setObjectName("gridProperties")
        self.adsorbateLineEdit = QtWidgets.QLineEdit(self.propertiesGroup)
        self.adsorbateLineEdit.setObjectName("adsorbateLineEdit")
        self.gridProperties.addWidget(self.adsorbateLineEdit, 2, 1, 1, 1)
        self.temperatureLabel = QtWidgets.QLabel(self.propertiesGroup)
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.gridProperties.addWidget(self.temperatureLabel, 3, 0, 1, 1)
        self.temperatureLineEdit = QtWidgets.QLineEdit(self.propertiesGroup)
        self.temperatureLineEdit.setObjectName("temperatureLineEdit")
        self.gridProperties.addWidget(self.temperatureLineEdit, 3, 1, 1, 1)
        self.textInfo = QtWidgets.QTextBrowser(self.propertiesGroup)
        self.textInfo.setObjectName("textInfo")
        self.gridProperties.addWidget(self.textInfo, 4, 0, 1, 2)
        self.materialBatchLineEdit = QtWidgets.QLineEdit(self.propertiesGroup)
        self.materialBatchLineEdit.setObjectName("materialBatchLineEdit")
        self.gridProperties.addWidget(self.materialBatchLineEdit, 1, 1, 1, 1)
        self.materialNameLineEdit = QtWidgets.QLineEdit(self.propertiesGroup)
        self.materialNameLineEdit.setObjectName("materialNameLineEdit")
        self.gridProperties.addWidget(self.materialNameLineEdit, 0, 1, 1, 1)
        self.materialBatchLabel = QtWidgets.QLabel(self.propertiesGroup)
        self.materialBatchLabel.setObjectName("materialBatchLabel")
        self.gridProperties.addWidget(self.materialBatchLabel, 1, 0, 1, 1)
        self.adsorbateLabel = QtWidgets.QLabel(self.propertiesGroup)
        self.adsorbateLabel.setObjectName("adsorbateLabel")
        self.gridProperties.addWidget(self.adsorbateLabel, 2, 0, 1, 1)
        self.materialNameLabel = QtWidgets.QLabel(self.propertiesGroup)
        self.materialNameLabel.setObjectName("materialNameLabel")
        self.gridProperties.addWidget(self.materialNameLabel, 0, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(self.propertiesGroup)
        self.cancelButton.setObjectName("cancelButton")
        self.gridProperties.addWidget(self.cancelButton, 5, 0, 1, 1)
        self.okButton = QtWidgets.QPushButton(self.propertiesGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setObjectName("okButton")
        self.gridProperties.addWidget(self.okButton, 5, 1, 1, 1)
        self.gridLayout.addWidget(self.propertiesGroup, 0, 10, 5, 1)

        self.graphGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphGroup.sizePolicy().hasHeightForWidth())
        self.graphGroup.setSizePolicy(sizePolicy)
        self.graphGroup.setObjectName("graphGroup")
        self.gridGraph = QtWidgets.QGridLayout(self.graphGroup)
        self.gridGraph.setObjectName("gridGraph")
        self.graphicsView = GraphView(self.graphGroup)
        self.graphicsView.setObjectName("graphicsView")
        self.gridGraph.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.graphGroup, 0, 11, 5, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 903, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCharact = QtWidgets.QMenu(self.menubar)
        self.menuCharact.setObjectName("menuCharact")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuModel = QtWidgets.QMenu(self.menubar)
        self.menuModel.setObjectName("menuModel")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/res/icons/10_Search_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")

        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/res/icons/04_Save_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")

        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/res/icons/14_Delete_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")

        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/res/icons/15_Tick_48x48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
    
        self.actionBET_Surface_Area = QtWidgets.QAction(MainWindow)
        self.actionBET_Surface_Area.setObjectName("actionBET_Surface_Area")
        self.actionLangmuir_Surface_Area = QtWidgets.QAction(MainWindow)
        self.actionLangmuir_Surface_Area.setObjectName("actionLangmuir_Surface_Area")
        self.actiont_plot = QtWidgets.QAction(MainWindow)
        self.actiont_plot.setObjectName("actiont_plot")
        self.actionalpha_s_plot = QtWidgets.QAction(MainWindow)
        self.actionalpha_s_plot.setObjectName("actionalpha_s_plot")
        self.actionMicroporous_PSD = QtWidgets.QAction(MainWindow)
        self.actionMicroporous_PSD.setObjectName("actionMicroporous_PSD")
        self.actionMesoporous_PSD = QtWidgets.QAction(MainWindow)
        self.actionMesoporous_PSD.setObjectName("actionMesoporous_PSD")
        self.actionDFT_Kernel_PSD = QtWidgets.QAction(MainWindow)
        self.actionDFT_Kernel_PSD.setObjectName("actionDFT_Kernel_PSD")
        self.actionModel_By = QtWidgets.QAction(MainWindow)
        self.actionModel_By.setObjectName("actionModel_By")
        self.actionGuess_Model = QtWidgets.QAction(MainWindow)
        self.actionGuess_Model.setObjectName("actionGuess_Model")

        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuCharact.addAction(self.actionBET_Surface_Area)
        self.menuCharact.addAction(self.actionLangmuir_Surface_Area)
        self.menuCharact.addSeparator()
        self.menuCharact.addAction(self.actiont_plot)
        self.menuCharact.addAction(self.actionalpha_s_plot)
        self.menuCharact.addSeparator()
        self.menuCharact.addAction(self.actionMicroporous_PSD)
        self.menuCharact.addAction(self.actionMesoporous_PSD)
        self.menuCharact.addAction(self.actionDFT_Kernel_PSD)
        self.menuModel.addAction(self.actionModel_By)
        self.menuModel.addAction(self.actionGuess_Model)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCharact.menuAction())
        self.menubar.addAction(self.menuModel.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "pyGAPS-gui", None, -1))
        self.propertiesGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "Isotherm Properties", None, -1))
        self.temperatureLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Temperature", None, -1))
        self.materialBatchLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Material Batch", None, -1))
        self.adsorbateLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Adsorbate", None, -1))
        self.materialNameLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Material Name", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("MainWindow", "Cancel", None, -1))
        self.okButton.setText(QtWidgets.QApplication.translate("MainWindow", "Freeze ->", None, -1))
        self.graphGroup.setTitle(QtWidgets.QApplication.translate("MainWindow", "Isotherm Overlay", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuCharact.setTitle(QtWidgets.QApplication.translate("MainWindow", "Characterization", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuModel.setTitle(QtWidgets.QApplication.translate("MainWindow", "Model", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionQuit.setText(QtWidgets.QApplication.translate("MainWindow", "Quit", None, -1))
        self.actionAbout.setText(QtWidgets.QApplication.translate("MainWindow", "About", None, -1))
        self.actionBET_Surface_Area.setText(QtWidgets.QApplication.translate("MainWindow", "BET Surface Area", None, -1))
        self.actionLangmuir_Surface_Area.setText(QtWidgets.QApplication.translate("MainWindow", "Langmuir Surface Area", None, -1))
        self.actiont_plot.setText(QtWidgets.QApplication.translate("MainWindow", "t-plot", None, -1))
        self.actionalpha_s_plot.setText(QtWidgets.QApplication.translate("MainWindow", "alpha-s plot", None, -1))
        self.actionMicroporous_PSD.setText(QtWidgets.QApplication.translate("MainWindow", "Microporous PSD", None, -1))
        self.actionMesoporous_PSD.setText(QtWidgets.QApplication.translate("MainWindow", "Mesoporous PSD", None, -1))
        self.actionDFT_Kernel_PSD.setText(QtWidgets.QApplication.translate("MainWindow", "DFT Kernel PSD", None, -1))
        self.actionModel_By.setText(QtWidgets.QApplication.translate("MainWindow", "Model Using", None, -1))
        self.actionGuess_Model.setText(QtWidgets.QApplication.translate("MainWindow", "Model Guess", None, -1))

import src.views.resources_rc
