name: CD-WINDOWS

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # - name: Use Cache
    #   id: cache-venv
    #   uses: actions/cache@v2
    #   with:
    #     path: ./.venv/
    #     key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-venv-

    # - name: Create venv
    #   run: |
    #     python -m venv ./.venv
    #     ./.venv/Scripts/activate
    #     pip install -r requirements.txt
    #     pip install .
    #   if: steps.cache-venv.outputs.cache-hit != 'true'

    # - name: Run PyInstaller
    #   run: |
    #     ./.venv/Scripts/activate
    #     pyinstaller pyGAPS-gui.spec

    # - name: Run Executable
    #   run: |
    #      cd ./dist/pyGAPS-gui
    #      pyGAPS-gui.exe

    - name: Set path for candle and light
      env:
        WIX_PATH: ${{ env.wix }}
      run: |
        echo "$env:WIX_PATH\bin"
        echo "$env:WIX_PATH\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: bash

    - name: Make MSI
      run: |
        python .\ci\collect_dist.py msi '.\dist\pyGAPS-gui*'
        candle.exe .\dist\pyGAPS-gui.wxs
        light.exe .\dist\pyGAPS-gui.wixobj -o .\dist\pyGAPS-gui.msi -ext WixUIExtension.dll

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: wininstaller
          path: dist/*.msi
          if-no-files-found: error
          retention-days: 1
