name: Deploy Mac

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Cache
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create venv
      run: |
        python -m venv ./.venv
        source ./.venv/bin/activate
        pip install -r requirements.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Run PyInstaller
      run: |
        source ./.venv/bin/activate
        pip install .
        pyinstaller pyGAPS-gui.spec

    # - name: Run Executable
    #   run: |
    #      cd ./dist/pyGAPS-gui*
    #      ./pyGAPS-gui.exe

    - name: Compress Executable
      run: |
        export DIST_FOLDER=$(ls ./dist | grep "pyGAPS-gui ")
        echo $DIST_FOLDER
        tar -zcvf "./dist/pyGAPS-gui-macos.tar.gz" "./dist/${DIST_FOLDER}"
        du -sh "./dist/pyGAPS-gui-macos.tar.gz"

    # - name: Upload Artifacts
    #   uses: actions/upload-artifact@v2
    #   with:
    #       name: mac
    #       path: dist/*.tar.gz
    #       if-no-files-found: error
    #       retention-days: 1

    - name: GH 🐱🐙 Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/pyGAPS-gui-macos.tar.gz
