name: Deploy Win

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      QT_API: pyside6 # make sure QT does not link something else

    steps:
    - uses: actions/checkout@v2

    - name: Manually fetch tags for semver
      run: git fetch --prune --unshallow

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: '**/setup.cfg'

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: build
        python-version: 3.8
        channels: conda-forge

    - name: Conda list
      run: |
        conda list
        conda install nomkl numpy scipy pandas
        conda list

    - name: Install
      run: |
        pip install .[build]
        conda list

    - name: Check install from cli
      run: |
        pygapsgui --test
        pygapsgui --version

    - name: Run PyInstaller
      run: |
        pyinstaller pyGAPS-gui.spec

    - name: Check bundled executable
      run: |
        cd dist/pyGAPS-gui*
        ./pyGAPS-gui.exe --version

    - name: Set path for candle and light
      run: echo "C:\Program Files (x86)\WiX Toolset v3.11\bin" >> $GITHUB_PATH
      shell: bash

    - name: Make MSI + ZIP
      run: |
        cd dist/pyGAPS-gui*
        $folderName = pwd
        cd ../..
        python ./ci/collect_dist.py msi zip $folderName
        candle.exe ./dist/pyGAPS-gui.wxs -o ./dist/pyGAPS-gui.wixobj
        light.exe ./dist/pyGAPS-gui.wixobj -o ./dist/pyGAPS-gui-win-x86_64.msi -ext WixUIExtension.dll
        Rename-Item -Path $folderName -NewName "pyGAPS-gui-win-x86_64.zip"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wininstaller
        path: dist/*.msi
        if-no-files-found: error
        retention-days: 1

    - name: GH 🐱🐙 Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/pyGAPS-gui-win-x86_64.msi
          ./dist/pyGAPS-gui-win-x86_64.zip
