name: Deploy Mac

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: '**/setup.cfg'

    - name: Install
      run: |
        pip list
        pip install .[build]

    - name: Run PyInstaller
      run: |
        pyinstaller pyGAPS-gui.spec

    # - name: Run Executable
    #   run: |
    #      cd ./dist/pyGAPS-gui*
    #      ./pyGAPS-gui.exe

    - name: Compress Executable
      run: |
        export DIST_FOLDER=$(ls ./dist | grep "pyGAPS-gui*.app ")
        echo $DIST_FOLDER
        cd ./dist
        zip -r "pyGAPS-gui-macos.zip" "${DIST_FOLDER}"
        du -sh "pyGAPS-gui-macos.zip"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: mac
          path: dist/*.zip
          if-no-files-found: error
          retention-days: 1

    - name: GH 🐱🐙 Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/pyGAPS-gui-macos.zip
