name: Deploy Mac

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      QT_API: pyside6 # make sure QT does not link something else

    steps:
    - uses: actions/checkout@v2

    - name: Manually fetch tags for semver
      run: git fetch --prune --unshallow

    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        cache: 'pip'
        cache-dependency-path: '**/setup.cfg'

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: build

    - name: Conda install
      run: |
        conda list
        conda install numpy scipy pandas nomkl
        conda list

    - name: Install
      run: |
        pip install .[build]
        conda list

    - name: Check install from cli
      run: |
        pygapsgui --test
        pygapsgui --version

    - name: Run PyInstaller
      run: |
        pyinstaller pyGAPS-gui.spec

    - name: Check bundled executable
      run: |
        cd dist/pyGAPS-gui*.app
        cd Contents/MacOS
        ./pyGAPS-gui --version

    - name: Compress executable
      run: |
        export DIST_FOLDER=$(ls ./dist | grep "pyGAPS-gui.*.app")
        echo $DIST_FOLDER
        cd ./dist
        zip -r "pyGAPS-gui-macos.zip" "${DIST_FOLDER}"
        du -sh "pyGAPS-gui-macos.zip"

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mac
        path: dist/*.zip
        if-no-files-found: error
        retention-days: 1

    - name: GH 🐱🐙 Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      with:
        files: |
          ./dist/pyGAPS-gui-macos.zip
