name: Deploy Linux

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Cache
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Install Apt Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libgl1-mesa-dev

    - name: Create venv
      run: |
        python -m venv ./.venv
        source ./.venvlin/bin/activate
        pip install -r requirements.txt
        pip install .
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Run PyInstaller
      run: |
        source ./.venv/bin/activate
        pyinstaller pyGAPS-gui.spec

    # - name: Run Executable
    #   run: |
    #      cd ./dist/pyGAPS-gui*
    #      xvfb-run pyGAPS-gui.exe

    - name: Compress Executable
      run: |
        export DIST_FOLDER=$(ls ./dist | grep pyGAPS)
        echo $DIST_FOLDER
        tar -zcvf $DIST_FOLDER.tar.gz $DIST_FOLDER
        du -sh $DIST_FOLDER.tar.gz

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: mac
          path: dist/*.tar.gz
          if-no-files-found: error
          retention-days: 1
