name: CD-WINDOWS

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Use Cache
      id: cache-venv
      uses: actions/cache@v2
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create venv
      run: |
        python -m venv ./.venv
        ./.venv/Scripts/activate
        pip install -r requirements.txt
        pip install .
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Run PyInstaller
      run: |
        ./.venv/Scripts/activate
        pyinstaller pyGAPS-gui.spec

    # - name: Run Executable
    #   run: |
    #      cd ./dist/pyGAPS-gui
    #      pyGAPS-gui.exe

    - name: Compress App
      run: |
        cd dist\pyGAPS-gui*
        $folderName = pwd | Select-Object | %{$_.ProviderPath.Split("\")[-1]}
        cd ..
        $zipName = $folderName + '.zip'
        Compress-Archive $folderName $zipName
        Write-Host((Get-Item $zipName).length/1MB)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
          name: winbuild_zip
          path: dist/*.zip
          if-no-files-found: error
          retention-days: 1
